language: node_js
node_js:
- 7
cache:
  yarn: true
  directories:
  - "~/.cache/yarn"
services:
- mongodb
after_success:
- npm run build
- './bin/travis-deploy.sh'
env:
  global:
  - GIT_USER: Travis CI
  - GIT_EMAIL: kamataryo@users.noreply.github.com
  - GH_REF: github.com/kamataryo/websocket-iot-ui.git
  - secure: cyvajD7izx3avhdUvPl1yN5EGXd7olEvAjXwU75iQFUBecSgMSFiybs2pdnk8evbX3YQKY+p3xbgQuScUDhf3TouburJf5ixJZttCh6GB7DtrKwevDMYi7OBrKl5SOjBePiqp8WaV9XRqAK3v+7F1CJngA9JdYtPGBlJqEJxh2AkFrTUe7Xve/DKOGtAhn2k8ZRq+wkodHIIT2JQVrJn/fyqaZiUfisnkVuFRU43Rwk71yBRCGUlNJaZhmN2VTzG5DhTlDDEeX10g8XCt0ufavDCSlv3IBGZpomcyIWfrvjFOxv8ydqX7wnlVzrHqV9uSYiLHYs1xX7yZTGAtkdWCPVKyp7XZvXMtUbnem3deHfu58we9jZ8/ww8QRWZGfoPP0PQw7rw1tb0FBW0HjfW5qbC3ROaO4Baubo0+R5EmsOiJe8S6sQhyHBxavftMRW5u0csyy/1e3XmsNO9QVPbFRogumST+T3VXDp8IOIQUZ1ksjufq5NOqP/1tzo1PoZ7EuIn9s2VI8Che7NuRqLwJrAItxIW6fmrhWb7UeoLTPl2RXS3jEESrUU6qGzLz2TfIqF5F3LH56b7ZMm3gXimL9sIIgX2FsogEmiQtkzEfIEpTxR0RN+1Adi7c3Kbm2GPwVYHBAgbtM4Cj1FuFzVVMkWV8xxZm8WUSAbYQX6aG7c=
